      double precision m0(NTOT), theta_0(NTOT, 200)
     $               , m1(NTOT), theta_1(NTOT, 200)
     $               , m2(NTOT), theta_2(NTOT, 200)
     $               , theta_p(NTOT, 200), theta_m(NTOT, 200)
      
      double precision p0(200)
      
      common/CISimpFitData/ m0, theta_0
     $                    , m1, theta_1
     $                    , m2, theta_2
     $                    , theta_p, theta_m
     $                    , p0

